image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - test
  - scan
  - publish
  - pages

include:
  # Python packages build,lint, test and publish
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/python.gitlab-ci.yml"

  # Docs pages
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/docs.gitlab-ci.yml"

  # Create Gitlab CI badges from CI metrics
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"

  # Create a release
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/release.gitlab-ci.yml"

python-test:
  services:
    - name: registry.gitlab.com/ska-telescope/ska-te-dish-structure-simulator/ska-te-ds-web-sim:0.11.0
      alias: cetc-simulator
      # Optionally specify command if needed
      # command: ["sh", "-c", "docker-entrypoint.sh"]
